site_name: Aeris Docs
site_url: https://aeris-docs.xyz
site_description: Documentation resources for Aeris
site_author: Alexander Þór

copyright: Open Source Under GNU/GPL 3.0

repo_url: https://github.com/Alexander-T-Moss/Aeris
repo_name: Aeris - GitHub

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

watch:
  - includes

theme:
  name: material
  icon:
    logo: octicons/cloud-16
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.footer
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share

draft_docs: |
  mkdocs-references.md

nav:
  - Welcome: index.md
  - Assembly Guides:
    - assembly-guides/index.md
    - AERIS: assembly-guides/aeris.md
    - AERIS Nano: assembly-guides/aeris-nano.md
  - Software Configuration:
    - software-config/index.md
    - ESPHome: software-config/esphome.md
    - Standalone (Local Web App): software-config/standalone.md
    - Zigbee Router: software-config/zigbee-router.md 
  - Freq. Asked Questions: faq.md
  - Understanding Readings:
    - readings/index.md
    - Temperature: readings/temperature.md
    - Humidity: readings/humidity.md
    - Particulate Matter: readings/pm.md
    - VOCs: readings/vocs.md
    - Nitrogen Oxide: readings/nox.md
    - Carbon Dioxide: readings/co2.md

  - Sensor Testing:
    - sensor-testing/index.md
    - SEN55: sensor-testing/sen55.md
    - SCD41: sensor-testing/scd41.md
    - BME280: sensor-testing/bme280.md
  - Alternatives: alternatives.md
  - Releases: https://github.com/Alexander-T-Moss/Aeris/releases
  - Contact: contact.md

not_in_nav: 
  mkdocs-references.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
            - includes/abbreviations.md
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - attr_list
  - tables
  - abbr
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: simple/printables
      link: https://www.printables.com/@AlexanderT_Moss
    - icon: simple/bambulab
      link: https://makerworld.com/en/@AlexanderT_Moss
    - icon: simple/github
      link: https://github.com/Alexander-T-Moss
  status:
    Draft: Draft

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - search
